### ISSUE TITLE
"This webpage has a redirect loop" after install

### ISSUE THREAD

**Issue by nguyentrongbang** [arrowjs/CMS#26]
I've installed CMS with database "mysql", but CMS does not install any sample data, it just creates data structure only.

So when I visit the admin page: http://localhost:8000/admin/login, the browse returns an error:

**This webpage has a redirect loop**

I dont know how to fix this. Does anyone have the same problem?

**Comment by trquoccuong** [comment]
We will check and feedback to you soon

**Comment by thangtyt** [comment]
We fixed this issue ,please pull new code .

**Comment by nguyentrongbang** [comment]
I've pulled new code, but the issue was not fixed. Still has error "This webpage has a redirect loop". Please check it again!

Here is log:

```
Error: ERR wrong number of arguments for 'set' command
    at JavascriptReplyParser._parseResult (c:\xampp\htdocs\CMS\node_modules\arro
wjs\node_modules\redis\lib\parsers\javascript.js:43:16)
    at JavascriptReplyParser.try_parsing (c:\xampp\htdocs\CMS\node_modules\arrow
js\node_modules\redis\lib\parsers\javascript.js:114:21)
    at JavascriptReplyParser.run (c:\xampp\htdocs\CMS\node_modules\arrowjs\node_
modules\redis\lib\parsers\javascript.js:126:22)
    at JavascriptReplyParser.execute (c:\xampp\htdocs\CMS\node_modules\arrowjs\n
ode_modules\redis\lib\parsers\javascript.js:107:10)
    at Socket.<anonymous> (c:\xampp\htdocs\CMS\node_modules\arrowjs\node_modules
\redis\index.js:131:27)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by thangtyt** [comment]
Can you give me some infomations about step by step you install ArrowCMS
(install nodejs > 4.0.0, postgresql 9.4 or mysql lastest version, clone code , edit config file and run "node server.js" command ?)

**Comment by nguyentrongbang** [comment]
I'm running on Windows environment: Xampp, NodeJs
- Mysql v5.6.16
- NodeJs v4.1.1
- Redis

Here is my steps:
- Step 1: Clone code from github
- Step 2: Edit configuration files:

**config/database.js**

```
"use strict";

module.exports = {
    db: {
        host: 'localhost',
        port: '3306',
        database: 'arrowjs',
        username: 'root',
        password: '',
        dialect: 'mysql',
        logging: true
    },
    associate: function (models) {
        models.menu.hasMany(models.menu_detail, {foreignKey: 'menu_id'});
        models.menu_detail.belongsTo(models.menu, {foreignKey: 'menu_id'});
        models.user.belongsTo(models.role, {foreignKey: 'role_id'});
        models.role.hasMany(models.user, {foreignKey: 'role_id'});
        models.post.belongsTo(models.user, {foreignKey: "created_by"})
    }
};
```

**config/redis.js**

```
'use strict';

module.exports = {
    redis: {
        host: 'localhost',
        port: '6379',
        type: 'redis'
    },
    redis_prefix: 'arrowCMS_',
    redis_key: {
        configs: 'site_setting',
        features: 'all_features',
        backend_menus: 'backend_menus',
        plugins: 'all_plugins'
    },
    redis_event: {
        update_config: 'config_update',
        update_feature: 'feature_update'
    }
};
```
- Step 3: Run

> npm install
- Step 4: Run 

> node server.js
- Step 5: Open home (admin) page: http://localhost:8000

At this step, error occur: 

> This webpage has a redirect loop

**Comment by nguyentrongbang** [comment]
I've switched to **postgres** database but have the same problem. It seems database has no sample data. Please provide the sample data so I can import it to the database. I don't see the sample data in the project yet.

`pg_restore -U [username] -d [dbname] "sql/arrowjs.backup"`

**Comment by thangtyt** [comment]
we recommend not using ArrowCMS on windows (recommend using linux or mac osx ) system.
but  i will check this problem soon for you.

**Comment by thangtyt** [comment]
Hi nguyentrongbang. 
This problem is Backslashes on windows and  forward slashes on linux systems . ArrowCMS is built on linux system so is error on windows . 
Our roadmap is not support on windows. 
Please install linux or mac osx

**Comment by nguyentrongbang** [comment]
Thank you, @thangtyt 

Can you fix this problem on Windows? I usually deploy web projects on Windows for easy testing or debuging.

I hope you can fix this error on Windows soon, so that more people can explore ArrowsCMS and make ArrowCMS is more popular.

**Comment by thangtyt** [comment]
There are many bugs on windows so i can't fix all. 
You can use linux for development or deployment (almost deploy on linux base).
NodeJs is Lightweight so you can install vmware to run.

**Comment by trquoccuong** [comment]
Hi , I fixed this bug. You need new version arrowjs core at least 0.4.3 . 
Try

```
npm i arrowjs // for update arrowjscore 
```

**Comment by nguyentrongbang** [comment]
Thank you for fixing, it worked! Now I can discover on Windows.

Anyway, could you please provide sample data for both of mysql and postgres database? I read the install instruction but not found file "sql/arrowjs.backup"

I cannot login to admin because there's no user data in table `arr_user`. How can I make my own admin account to login into admin page?

**Comment by trquoccuong** [comment]
arrowCMS not need sample database. The first time you login to admin page, Arrow will create an account for you.

**Comment by nguyentrongbang** [comment]
Would you mind if I contact you via email? I think there're still many bugs on this release. I will report bugs directly to you instead of posting to this topic. If can, please provide your email, I will contact to your email.

**Comment by TechMaster** [comment]
Please always use GitHub to issue new bug. We will fix all because we use
this framework in many of our own products
